In [1]:
!pwd

/home/studio-lab-user/Blackbox-Coresets-VI


In [2]:
# TODO: move to requirements.txt, otherwise we need to do pip install .
# for every change we make to the code

In [2]:
import os 
import sys
sys.path.append("/home/studio-lab-user/Blackbox-Coresets-VI")

### MNIST Random Fixed U

In [4]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 20 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata\
--mfvi_selection_method "kmeans" --num_trials 1 


Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4., 5., 5., 5.,
        6., 6., 6., 7., 7., 7., 8., 8., 8., 9., 9., 9.])
  0%|                                                    | 0/20 [00:00<?, ?it/s]
predictive accuracy: 9.30%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.o

### MNIST Random Evaluation

In [12]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 2 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved \
--mfvi_selection_method "kmeans" --num_trials 1 


Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on MNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4., 5., 5., 5.,
        6., 6., 6., 7., 7., 7., 8., 8., 8., 9., 9., 9.])
  0%|                                                     | 0/2 [00:00<?, ?it/s]
predictive accuracy: 9.37%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/st

### MNIST Kmeans 

In [ ]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 80 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "kmeans" --num_trials 1 



Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 80 datapoints
SETTING UP THE MODEL 


Points from this cluster: [15814 29067 24105 32383]
Points from this cluster: [50480  5298 49770 28357]
Points from this cluster: [ 5507  3956  5235 57453]
Points from this cluster: [38432 36682 38985  7574]
Points from this cluster: [50575 42830 13491 10411]
Points from this cluster: [19694 20550 58710  9472]
Points from this cluster: [58760 10415  5542 54898]
Points from this cluster: [ 7106 21420 31720 24119]
Points from this cluster: [52260  4318 23713 21246]
Points from this cluster: [28599  4549 18473 38286]
Points from this cluster: [51874 34857 13796 32141]
Points from this cluster: [ 5984 36579 14689 31982]
Points from this cluster: [12980 44755  3043 14921]
Points f

### CIFAR Resnet Random

In [3]:
!python3 psvi_experiments.py --datasets "Cifar10" \
--architecture "resnet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 2 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved \
--mfvi_selection_method "kmeans" --num_trials 1 



Reading/Generating the dataset CIFAR10
Details about dataset: Total Datapoints: 50000, Dimensions: 32, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on Cifar10 data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4., 5., 5., 5.,
        6., 6., 6., 7., 7., 7., 8., 8., 8., 9., 9., 9.], device='cuda:0')
  0%|                                                   | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 670, in <module>
    (experiment_driver(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 464, in experiment_driver
    results[dnm][nm_alg][ps][t] = inf_alg(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 392, in <lambda>
    lambda *args, **kwargs: PSVIEvaluate(*args, **kwargs).r

### MNIST Random Evaluation from MFVI

In [5]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 21 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --save_new_folder --log_pseudodata\
--mfvi_selection_method "random" --num_trials 1 


Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on MNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


Chosen indices: [40348, 13830, 52831, 53817, 38826, 51261, 16386, 48622, 2029, 50835, 48180, 50295, 31707, 26402, 39835, 39375, 48335, 9345, 45157, 6111, 38940, 31834, 49784, 4750, 20389, 56222, 13120, 23526, 30968, 6920]
tensor([1, 0, 0, 8, 2, 4, 3, 7, 3, 4, 0, 2, 9, 6, 7, 4, 1, 8, 6, 8, 5, 9, 5, 1,
        9, 2, 5, 7, 6, 3])
  0%|                                                    | 0/20 [00:00<?, ?it/s]
predictive accuracy: 9.43%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `op

### Others

In [11]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi_selection" \
--log_every 100 --num_epochs 100 --mc_samples 256 --inner_it 20 --lr0net 1e-2 \
--coreset_sizes 40 --init_at "subsample" \
--pretrain_epochs 1 --load_from_saved\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--distance_fn "cosine" \
--mfvi_selection_method "kmeans" --num_trials 1 


Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI_SELECTION on webspam data over 1 trial.





Running mfvi_selection

Trial #0
Coreset/Subset with 40 datapoints
center list: [13636, 20830, 37916, 44636, 8676, 44907, 47586, 26873, 5055, 12829, 17128, 48592, 48892, 26005, 11495, 44475, 18347, 5160, 9294, 30270]
center list: [1763, 54327, 233, 4534, 50602, 51302, 65955, 9377, 74858, 58265, 51885, 15594, 16838, 63479, 17713, 58101, 26123, 73842, 72701, 29468]
[13636, 20830, 37916, 44636, 8676, 44907, 47586, 26873, 5055, 12829, 17128, 48592, 48892, 26005, 11495, 44475, 18347, 5160, 9294, 30270, 1763, 54327, 233, 4534, 50602, 51302, 65955, 9377, 74858, 58265, 51885, 15594, 16838, 63479, 17713, 58101, 26123

### MNIST KMeans Evaluate

In [8]:
!python3 psvi_experiments.py --datasets "FashionMNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 21 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "kmeans" --num_trials 1 


Reading/Generating the dataset FASHIONMNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on FashionMNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


Chosen indices: [45276, 57929, 21507, 37901, 10757, 15112, 8385, 30591, 14062, 39524, 44452, 32751, 55800, 43718, 50230, 41513, 28333, 33195, 55724, 26634, 50673, 10269, 22899, 27421, 30577, 3169, 51726, 23111, 12043, 36232]
tensor([0, 9, 4, 3, 8, 8, 9, 3, 5, 7, 1, 5, 2, 4, 7, 6, 0, 9, 2, 1, 6, 6, 3, 2,
        8, 1, 0, 7, 5, 4])
  0%|                                                    | 0/21 [00:00<?, ?it/s]
predictive accuracy: 9.79%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the op

### Scored KMeans Entropy

In [21]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 101 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 80 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "scored_kmeans_entropy" --num_trials 1


Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on MNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 80 datapoints
SETTING UP THE MODEL 


/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/utils.py:944: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs_prob = softmax_fn(output)
[ 619 2749  974 2836]
[ 116 2098  376 2094]
[ 746 1592  145 1894]
[3239 1846 1107  257]
[2489  743  128 2327]
[ 111  953 2122   75]
[2721 1605  945 2658]
[1236 1105 1128 1619]
[ 759  206  632 1994]
[  10 3222 2776  580]
[ 241 2905 3151 1343]
[ 378 1814 1249 1495]
[ 428  151  701 2115]
[ 137 2583 2725 2715]
[1273 1278 1614  306]
[2296 2047  432 2110]
[2463 2241  965 3755]
[ 643 1384 1728  384]
[ 152  799 2146 2603]
[2264 2549 2429 2035]
Chosen indices: [11794, 4

### Other methods

In [19]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 101 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 80 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "least_confidence" --num_trials 1


Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on MNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 80 datapoints
SETTING UP THE MODEL 


Chosen indices: [999, 5942, 42114, 49003, 10995, 47283, 55395, 8300, 52141, 9661, 191, 14280, 943, 58539, 31255, 41192, 25783, 35301, 1904, 50025, 36638, 30198, 45526, 50473, 54929, 52757, 50536, 13150, 18712, 53852, 15562, 19924, 2220, 27204, 57909, 55310, 50520, 23770, 56714, 33510, 47951, 4334, 34919, 46976, 27848, 14936, 40191, 16320, 19264, 41785, 9294, 19252, 46115, 37921, 28260, 49919, 16997, 6600, 17188, 46383, 19886, 27730, 59354, 24, 51536, 55258, 22650, 20464, 22976, 22743, 27455, 27210, 54778, 5113, 25504, 53682, 32309, 25568, 33437, 17583]
tensor([6, 3, 3, 9, 5, 8, 8, 8, 6, 8, 5, 7, 0, 9, 6, 4, 0, 2, 0, 3, 5, 4, 5, 9,
        6, 2, 7, 7, 0, 7, 9, 0, 4, 6, 3, 1, 7, 2, 1, 3,

### Rest of them

In [23]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi_subset"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 10 --num_epochs 50 --mc_samples 256 --inner_it 1000 --lr0net 1e-2\
--save_new_folder\
--coreset_sizes 40 80 --init_at "subsample" --num_trials 3 


Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI_SUBSET on webspam data over 3 independent trials.





Running mfvi_subset

Trial #0
Coreset/Subset with 40 datapoints
100%|█████████████████████████████████████████| 100/100 [00:14<00:00,  6.97it/s]
Trial completed!

Coreset/Subset with 80 datapoints
100%|█████████████████████████████████████████| 100/100 [00:12<00:00,  7.82it/s]
Trial completed!

Trial #1
Coreset/Subset with 40 datapoints
100%|█████████████████████████████████████████| 100/100 [00:13<00:00,  7.50it/s]
Trial completed!

Coreset/Subset with 80 datapoints
100%|█████████████████████████████████████████| 100/100 [00:14<00:00,  7.11it/s]
Trial completed!

Trial #2
Coreset/Subset with 40 da

In [3]:
!python3 psvi_experiments.py --datasets "Cifar10" \
--architecture "lenet" --n_hidden 100 --methods "psvi_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 10 --num_epochs 50 --mc_samples 10 --inner_it 100 --lr0net 1e-2\
--coreset_sizes 40 --init_at "subsample" --num_trials 1 


Reading/Generating the dataset CIFAR10
Details about dataset: Total Datapoints: 50000, Dimensions: 32, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_FIXED_U on Cifar10 data over 1 trial.





Running psvi_fixed_u

Trial #0
Coreset/Subset with 40 datapoints
SETTING UP THE MODEL 


  0%|                                                    | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 664, in <module>
    (experiment_driver(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 458, in experiment_driver
    results[dnm][nm_alg][ps][t] = inf_alg(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 383, in <lambda>
    lambda *args, **kwargs: PSVIFixedU(*args, **kwargs).run_psvi(*args, **kwargs)
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/psvi_classes.py", line 762, in run_psvi
    test_acc, test_nll, iw_

In [ ]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "sparsevi"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 10 --num_epochs 50 --mc_samples 256 --inner_it 200 \
--outer_it 400 --lr0net 1e-2 --save_new_folder\
--coreset_sizes 40 80 --init_at "random" --num_trials 1 


Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via SPARSEVI on webspam data over 1 trial.





Running sparsevi

Trial #0
Unconstrained data access
100%|████████████████████████████████████████| 50/50 [2:01:07<00:00, 145.36s/it]
Trial completed!



In [2]:
!python3 psvi_experiments.py --datasets "halfmoon" \
--architecture "fn" --n_hidden 100 --methods "mfvi_subset"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 50 --num_epochs 101 --mc_samples 64 --inner_it 500 --lr0net 1e-2 \
--init_sd 1e-3 --data_minibatch 256 --log_pseudodata\
--save_new_folder \
--coreset_sizes 10 --init_at "subsample" --num_trials 1 


Reading/Generating the dataset HALFMOON
Details about dataset: Total Datapoints: 800, Dimensions: 2, num classes: 2

Bayesian neural network experiment.
Inference via MFVI_SUBSET on halfmoon data over 1 trial.





Running mfvi_subset

Trial #0
Coreset/Subset with 10 datapoints
  0%|                                                   | 0/202 [00:00<?, ?it/s]/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
predictive accuracy: 83.00%
100%|█████████████████████████████████████████| 202/202 [00:41<00:00,  4.90it/s]
Trial completed!



In [3]:
!python3 psvi_experiments.py --datasets "halfmoon" \
--architecture "fn" --n_hidden 100 --methods "mfvi_selection" \
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 50 --num_epochs 101 --mc_samples 64 --inner_it 500 --lr0net 1e-2 \
--init_sd 1e-3 --data_minibatch 256 --log_pseudodata \
--pretrain_epochs 5 \
--save_new_folder --load_from_saved \
--mfvi_selection_method "el2n" \
--coreset_sizes 10 --init_at "subsample" --num_trials 1 


Reading/Generating the dataset HALFMOON
Details about dataset: Total Datapoints: 800, Dimensions: 2, num classes: 2

Bayesian neural network experiment.
Inference via MFVI_SELECTION on halfmoon data over 1 trial.





Running mfvi_selection

Trial #0
Coreset/Subset with 10 datapoints
/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/utils.py:793: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs_prob = softmax_fn(output)
  0%|                                                   | 0/202 [00:00<?, ?it/s]predictive accuracy: 29.00%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|█████████████████████████████

In [10]:
!python3 psvi_experiments.py --datasets "halfmoon" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 50 --num_epochs 101 --mc_samples 64 --inner_it 500 --lr0net 1e-2 \
--init_sd 1e-3 --data_minibatch 256\
--log_pseudodata\
--coreset_sizes 40 --init_at "subsample" --num_trials 1 


Reading/Generating the dataset HALFMOON
Details about dataset: Total Datapoints: 800, Dimensions: 2, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI on halfmoon data over 1 trial.





Running mfvi

Trial #0
Unconstrained data access
  0%|                                                   | 0/202 [00:00<?, ?it/s]/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
predictive accuracy: 82.00%
 95%|██████████████████████████████████████▉  | 192/202 [00:02<00:00, 99.01it/s]predictive accuracy: 84.50%
predictive accuracy: 84.50%
100%|█████████████████████████████████████████| 202/202 [00:02<00:00, 74.42it/s]
Trial completed!



In [7]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --num_trials 1 




Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


  0%|                                                   | 0/100 [00:00<?, ?it/s]
predictive accuracy: 9.43%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. 

In [10]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "psvi_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 10 --num_epochs 50 --mc_samples 256 --inner_it 500 --lr0net 1e-2\
--coreset_sizes 30 --init_at "subsample" --num_trials 1 




Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via PSVI_FIXED_U on webspam data over 1 trial.





Running psvi_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


  0%|                                                    | 0/50 [00:00<?, ?it/s]
predictive accuracy: 39.18%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details 

In [7]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi_subset"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 10 --num_epochs 50 --mc_samples 256 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 40 --init_at "subsample" --num_trials 1 



Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI_SUBSET on webspam data over 1 trial.





Running mfvi_subset

Trial #0
Coreset/Subset with 40 datapoints
100%|█████████████████████████████████████████| 100/100 [00:15<00:00,  6.59it/s]
Trial completed!



In [5]:
!python3 psvi_experiments.py --datasets "webspam" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi_selection"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 40 --num_epochs 100 --mc_samples 256 --inner_it 20 --lr0net 1e-2\
--coreset_sizes 40 --init_at "subsample"\
--pretrain_epochs 2 --load_from_saved\
--mfvi_selection_method "scored_random_entropy" --num_trials 1



Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI_SELECTION on webspam data over 1 trial.





Running mfvi_selection

Trial #0
Coreset/Subset with 40 datapoints
/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/utils.py:767: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs_prob = softmax_fn(output)
100%|█████████████████████████████████████████| 200/200 [00:04<00:00, 42.64it/s]
Trial completed!



In [2]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "logistic_regression" --n_hidden 100 --methods "mfvi_selection"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 40 --num_epochs 100 --mc_samples 256 --inner_it 20 --lr0net 1e-2\
--coreset_sizes 40 --init_at "subsample"\
--mfvi_selection_method "scored_kmeans_el2n" --num_trials 1 



Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian logistic regression experiment.
Inference via MFVI_SELECTION on MNIST data over 1 trial.





Running mfvi_selection

Trial #0
Coreset/Subset with 40 datapoints
  0%|                                                     | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 603, in <module>
    (experiment_driver(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 420, in experiment_driver
    results[dnm][nm_alg][ps][t] = inf_alg(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/baselines.py", line 1764, in run_selection_with_mfvi
    mfvi_select.select_data()
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/baselines.py", line 1605, in select_data
    select_method.pretrain(
  File "/home/studio-lab-user/Blackbox-Corese

In [2]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "mfvi_selection"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--log_every 40 --num_epochs 100 --mc_samples 256 --inner_it 20 --lr0net 1e-2\
--coreset_sizes 30 --init_at "subsample" \
--load_from_saved \
--mfvi_selection_method "submodular" --pretrain_epochs 5 --num_trials 1



Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via MFVI_SELECTION on MNIST data over 1 trial.





Running mfvi_selection

Trial #0
Coreset/Subset with 30 datapoints
^C
Traceback (most recent call last):
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 664, in <module>
    (experiment_driver(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi_experiments.py", line 458, in experiment_driver
    results[dnm][nm_alg][ps][t] = inf_alg(
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/baselines.py", line 1951, in run_selection_with_mfvi
    mfvi_select.select_data()
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/baselines.py", line 1617, in select_data
    select_method.select_data()
  File "/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/utils.py", line 1230, in select_data
    self.chosen_datas

In [5]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "kmeans" --num_trials 1 



Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4., 5., 5., 5.,
        6., 6., 6., 7., 7., 7., 8., 8., 8., 9., 9., 9.], device='cuda:0')
  0%|                                                   | 0/100 [00:00<?, ?it/s]
predictive accuracy: 9.43%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at 

In [6]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "custom" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved --log_pseudodata --save_new_folder\
--mfvi_selection_method "kmeans" --num_trials 1 



Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


Chosen indices: [4738, 29292, 59232, 22770, 49088, 30967, 6166, 47643, 9743, 55829, 26531, 6853, 26157, 14966, 12304, 25037, 42488, 32930, 45943, 35396, 46590, 52265, 41820, 56752, 6938, 29375, 39326, 40387, 19973, 21973]
tensor([0, 9, 4, 3, 8, 8, 9, 3, 5, 7, 1, 5, 2, 4, 7, 6, 0, 9, 2, 1, 6, 6, 3, 2,
        8, 1, 0, 7, 5, 4])
  0%|                                                   | 0/100 [00:00<?, ?it/s]
predictive accuracy: 9.33%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite 

In [14]:
!python3 psvi_experiments.py --datasets "MNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_alpha_fixed_u"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "custom" \
--mfvi_selection_method "scored_kmeans_least_confidence" --num_trials 1 




Reading/Generating the dataset MNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_ALPHA_FIXED_U on MNIST data over 1 trial.





Running psvi_alpha_fixed_u

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


  0%|                                                   | 0/100 [00:00<?, ?it/s]
predictive accuracy: 9.43%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. 

In [3]:
!python3 psvi_experiments.py --datasets "FashionMNIST" \
--architecture "lenet" --n_hidden 100 --methods "psvi_evaluate"\
--data_folder "/home/studio-lab-user/all_data/vi_data" \
--results_folder "/home/studio-lab-user/all_data/vi_result" \
--learn_z --data_minibatch 256 --lr0u 1e-2 --lr0v 1e-2 --lr0z 1e-2 --lr0alpha 1e-3\
--log_every 10 --num_epochs 100 --mc_samples 10 --inner_it 20 --lr0net 1e-3\
--coreset_sizes 30 --init_at "subsample" --distance_fn "cosine"\
--pretrain_epochs 5 --load_from_saved \
--mfvi_selection_method "kmeans" --num_trials 1 



Reading/Generating the dataset FASHIONMNIST
Details about dataset: Total Datapoints: 60000, Dimensions: 28, num classes: 10

Bayesian neural network experiment.
Inference via PSVI_EVALUATE on FashionMNIST data over 1 trial.





Running psvi_evaluate

Trial #0
Coreset/Subset with 30 datapoints
SETTING UP THE MODEL 


tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4., 5., 5., 5.,
        6., 6., 6., 7., 7., 7., 8., 8., 8., 9., 9., 9.])
  0%|                                                   | 0/100 [00:00<?, ?it/s]
predictive accuracy: 9.52%
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytor

3.81494140625

In [4]:
# run all experiments for webspam
#selection_method = [
#    "kmeans", "random", "el2n", "least_confidence", "entropy", "forgetting",
#    "scored_kmeans_el2n", "scored_kmeans_forgetting", 
#    "scored_kmeans_entropy", "scored_kmeans_least_confidence"
#]

selection_method = [
    "scored_kmeans_entropy", "scored_kmeans_least_confidence"
]

lr_list = [1e-2, 1e-3]

In [5]:
for this_selection in selection_method:
    for lr in lr_list:
        !python3 psvi_experiments.py --datasets "webspam" \
        --architecture "logistic_regression" --n_hidden 100 --methods "mfvi_selection"\
        --data_folder "/home/studio-lab-user/all_data/vi_data" \
        --results_folder "/home/studio-lab-user/all_data/vi_result" \
        --log_every 100 --num_epochs 200 --mc_samples 256 --inner_it 20 --lr0net {lr}\
        --coreset_sizes 10 40 100 --init_at "subsample"\
        --save_new_folder\
        --mfvi_selection_method {this_selection} --num_trials 3 



Reading/Generating the dataset WEBSPAM
X is either low-dimensional or not very sparse, so converting to a numpy array
X is either low-dimensional or not very sparse, so converting to a numpy array
Details about dataset: Total Datapoints: 126185, Dimensions: 128, num classes: 2

Bayesian logistic regression experiment.
Inference via MFVI_SELECTION on webspam data over 3 independent trials.





Running mfvi_selection

Trial #0
Coreset/Subset with 10 datapoints
100%|█████████████████████████████████████████████| 4/4 [01:49<00:00, 27.31s/it]
/home/studio-lab-user/Blackbox-Coresets-VI/psvi/inference/utils.py:640: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs_prob = softmax_fn(output)
100%|█████████████████████████████████████████| 400/400 [00:11<00:00, 34.97it/s]
Trial completed!

Coreset/Subset with 40 datapoints
100%|█████████████████████████████████████████████| 4/4 [02:02<00:00, 30.69s/it]
/home/studi

In [6]:
selection_method = [
    "kmeans", "scored_kmeans_forgetting"
]

lr_list = [1e-2, 1e-3]

In [ ]:
for this_selection in selection_method:
    for lr in lr_list:
        !python3 psvi_experiments.py --datasets "MNIST" \
        --architecture "lenet" --n_hidden 100 --methods "mfvi_selection"\
        --data_folder "/home/studio-lab-user/all_data/vi_data" \
        --results_folder "/home/studio-lab-user/all_data/vi_result" \
        --log_every 100 --num_epochs 200 --mc_samples 256 --inner_it 20 --lr0net {lr}\
        --coreset_sizes 10 40 100 --init_at "subsample"\
        --save_new_folder\
        --mfvi_selection_method {this_selection} --num_trials 3 


In [9]:
read_dataset("phishing", method_args)

(tensor([[-0.1355, -0.2142,  0.1337,  ..., -0.4177, -0.1291,  1.0000],
         [ 0.2366, -0.0285, -0.0551,  ..., -0.0268, -0.4718,  1.0000],
         [ 0.1945, -0.0089,  0.0135,  ..., -0.0408, -0.5287,  1.0000],
         ...,
         [-0.1364, -0.1582,  0.0703,  ..., -0.1382, -0.3796,  1.0000],
         [ 0.1848, -0.0526,  0.0829,  ...,  0.0579, -0.5467,  1.0000],
         [ 0.1889,  0.0078, -0.0184,  ...,  0.0178, -0.5397,  1.0000]]),
 tensor([1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
         1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
         0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
         1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
         1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
         1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
         0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1.,

In [7]:
import os 
import pickle
results_folder = "/home/studio-lab-user/all_data/vi_result"
result_file = 'results.pk'
full_fname = os.path.join(results_folder, result_file)
car_pickle = open (full_fname, "rb")
car_contents = pickle.load(car_pickle)


AttributeError: Can't get attribute 'rec_dd' on <module '__main__'>

In [20]:
for x in range(5):
    !python3 add_numbers.py -n {x}


Number of items: 1
Number of items: 2
Number of items: 3
Number of items: 4
